apiVersion: v1
kind: Service
metadata:
  labels:
    app: git-server
  name: git-server
spec:
  type: LoadBalancer
  ports:
    - name: '2222'
      port: 2222
      targetPort: 22
  selector:
    app: git-server
