apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: git-server-claim1
  name: git-server-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
